# Generated by Django 6.0.6 on 2026-07-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bill_type',
            field=models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2')], default='type1', max_length=10),
        ),
    ]
