# Generated by Django 6.0.6 on 2026-07-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_bill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('delivery', 'Delivery'), ('customer', 'Customer')], db_index=True, default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='store_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
