# Generated by Django 6.0.6 on 2026-07-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role_alter_user_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paginate_dashboard',
            field=models.BooleanField(default=True),
        ),
    ]
