# Generated by Django 6.0.6 on 2026-08-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_paginate_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_settle_old_balance',
            field=models.BooleanField(default=True),
        ),
    ]
