# Generated by Django 6.0.6 on 2026-06-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_draft_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivered_at',
            new_name='completed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='packed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='received_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
