# Generated by Django 6.0.6 on 2026-06-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_delivered_at_order_completed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed_at',
            new_name='received_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
