# Generated by Django 6.0.6 on 2026-07-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_original_old_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processing_time_ms',
            field=models.IntegerField(blank=True, help_text='Time taken to process the order on the server', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], db_index=True, default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='received_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='store_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
